services:

  backend:
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - alembic
    
  alembic:
    build:
      context: .
      dockerifle: Dockerfile
    env_file:
      - .env
    command: alembic upgrade head

networks:
  traefik-public:
    external: false
