services:

  moyeo-backend:
    ports:
      - "80:80"
    depends_on:
      - alembic
    command: /start-reload.sh
    environment:
      - LOG_LEVEL=debug
      - PRE_START_PATH=/prestart.sh

networks:
  traefik-public:
    external: false
