"""Create VoteSchedule, VoteParticipant

Revision ID: 4f8e31963327
Revises: 099438a165ce
Create Date: 2023-04-30 23:12:46.656317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f8e31963327'
down_revision = '099438a165ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voteschedule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('periods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['partyuser.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voteparticipant',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vote_schedule_id', sa.Integer(), nullable=True),
    sa.Column('party_user_id', sa.Integer(), nullable=True),
    sa.Column('periods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['party_user_id'], ['partyuser.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vote_schedule_id'], ['voteschedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voteparticipant')
    op.drop_table('voteschedule')
    # ### end Alembic commands ###
