"""Fix Party

Revision ID: 7d0d6444d96e
Revises: fdbc69696ca6
Create Date: 2023-02-19 02:01:38.203150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d0d6444d96e'
down_revision = 'fdbc69696ca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('party_leader_id_fkey', 'party', type_='foreignkey')
    op.create_foreign_key(None, 'party', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('party', 'leader_id')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column('party', sa.Column('leader_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'party', type_='foreignkey')
    op.create_foreign_key('party_leader_id_fkey', 'party', 'user', ['leader_id'], ['id'], ondelete='SET NULL')
    op.drop_column('party', 'user_id')
    # ### end Alembic commands ###
