"""Fix fk

Revision ID: c05656d1efc4
Revises: 7d0d6444d96e
Create Date: 2023-02-19 02:15:52.203363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05656d1efc4'
down_revision = '7d0d6444d96e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('leader_id', sa.Integer(), nullable=True))
    op.drop_constraint('party_user_id_fkey', 'party', type_='foreignkey')
    op.create_foreign_key(None, 'party', 'user', ['leader_id'], ['id'], ondelete='SET NULL')
    op.drop_column('party', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'party', type_='foreignkey')
    op.create_foreign_key('party_user_id_fkey', 'party', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('party', 'leader_id')
    # ### end Alembic commands ###
